### ISSUE TITLE
Error loading in Home Assistant 2021.2.0b1

### ISSUE THREAD

**Issue by BoneheadFraggle** [elad-bar/ha-blueiris#99]
Last known working HA version: 2021.1.5

After upgrade to 2021.2.0b1:
```Setup failed for blueiris: Unable to import component: cannot import name 'CONF_PAYLOAD_AVAILABLE' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)```

**Comment by elad-bar** [comment]
Dup #98 

Thanks for the heads-up
