### ISSUE TITLE
Intergration not working in 2023.5 home assistant update

### ISSUE THREAD

**Issue by Coo902418** [elad-bar/ha-blueiris#207]
Intergration not loaded in 2023.5 update. Was working in previous release.
Error logs:

Logger: homeassistant.setup
Source: setup.py:214
First occurred: 19:24:18 (1 occurrences)
Last logged: 19:24:18

Setup failed for custom integration blueiris: Unable to import component: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
